server:
  port: 9010
spring:
  main:
    allow-circular-references: 'true'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: userprofile-service
  datasource:
    password: Vihaan@2020
    username: root
    url: jdbc:mysql://localhost:3306/newsdb
  jackson:
    serialization:
      fail-on-empty-beans: 'false'
eureka:
  instance:
    preferIpAddress: 'true'
  client:
    fetchRegistry: 'true'
    registerWithEureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
jwt:
  signing:
    key: ymLTU8rq83j4fmJZj60wh4OrMNuntIj4fmJ
springdoc:
  version: 1.6.11
