apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    app: eureka-service
spec:
  type: ClusterIP
  selector:
    app: eureka-service
  ports:
  - protocol: TCP
    port: 8070
    targetPort: 8070
