apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
  labels:
    app: userprofile-service
spec:
  type: ClusterIP
  selector:
    app: userprofile-service
  ports:
  - protocol: TCP
    port: 9010
    targetPort: 9010
